### PR TITLE
Merge pull request 2

### PR DESCRIPTION
**Pull request by zjhxmjl**

### CODE REVIEW

**Comment by omarpiani** [comment]
Some difficulties @zjhxmjl ? fork this repository in your own. Make a commit, after that make PR.

**Comment by zjhxmjl** [comment]
@omarpiani sorry,I'm not familiar with the git command

**Comment by omarpiani** [comment]
From github website is quite simple and intuitive.
Take a look to this 2 min vid: https://www.youtube.com/watch?v=yr6IzOGoMsQ

**Comment by zjhxmjl** [comment]
thks!

**Pull request closed without merging**
